layout_spectrum: 1
typography_spectrum: 0.9992264
color:
  saturation: 1
  brandStrength: 0.9025099
  lightness: 0.05017921
  rhythmicContrast: 0.4756074
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Lalunafilms.com
